laboratorio/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views.errors import CustomErrorServer

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('laboratory.urls'))
]


handler404 = CustomErrorServer.error_404
handler403 = CustomErrorServer.error_403
handler500 = CustomErrorServer.error_500

laboratory/urls.py
from django.urls import path
from laboratory.views.list_lab import List_Lab

app_name = 'laboratorio'

urlpatterns = [
    path('<int:pk>/', List_Lab.as_view(), name='list_lab')
]

main/urls.py
from django.urls import path
from .views.index import Index
from .views.login import Login
from .views.signup import Signup
from .views.update_user import UpdateUser
from .views.dashboard import Dashboard
from .views.logout import Logout


urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('signup/', Signup.as_view(), name='signup'),
    path('dashboard/<str:username>/', Dashboard.as_view(), name='dashboard'),
    path('atualizar/cadastro/<int:pk>', UpdateUser.as_view(), name='updateuser'),
]

revisao/sistema_escolar/setup/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from escola.views import AlunosViewSet, CursosViewSet



router = routers.DefaultRouter()
router.register('alunos', AlunosViewSet, basename='Alunos')
router.register('cursos', CursosViewSet, basename='Cursos')






urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(router.urls)),

]

main/forms/login_forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Nome do usuário'}),
                               max_length=30,)
    
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Senha'}),
        strip=False
        )

main/forms/signup_forms.py
from django import forms


class SignupForms(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username'}),
        max_length=30)
    
    password1 =  forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Senha'}),
        max_length=30)
    
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'forms-control', 'placeholder': 'Confirme a senha'}),
        max_length=30)

main/forms/updateuser_forms.py
from django import forms
from ..models import Usuario

class UserUpdateForm(forms.ModelForm):
    USUARIO = [
        (1, 'Aluno'),
        (2, 'Professor')
    ]

    ATIVO_INATIVO = [
            (1, 'Ativo'),
            (2, 'Inativo')
        ]
    

    class Meta:
        model= Usuario
        fields = ['username', 'first_name', 'last_name', 'email', 'is_active', 'user', 'cpf_cnpj', 'phone']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Nome de usuário'}),
            'first_name': forms.TextInput(attrs={'placeholder': 'Primeiro nome'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Sobrenome'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Endereço de email'}),
            'cpf_cnpj': forms.TextInput(attrs={'placeholder': 'CPF/CNPJ'}),
            'phone': forms.TextInput(attrs={'placeholder': 'Telefone'}),
        }

    user = forms.ChoiceField(
        choices=[('', 'Selecione...')] + USUARIO, 
        widget=forms.Select(attrs={'placeholder': 'Usuário'})
    )
    is_active = forms.BooleanField(
        label='Status',
        required=False,
        widget=forms.CheckboxInput(attrs={'class': 'custom-class'}),
    )

laboratory/views/list_lab.py
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from laboratory.models import Laboratory
from django.shortcuts import render, get_object_or_404
from laboratory.forms.schedule_lab_form import ScheduleLabForm


class List_Lab(LoginRequiredMixin, View):

    def get(self, request, pk):
        lab = get_object_or_404(Laboratory, pk=pk)
        form = ScheduleLabForm()
        context = {'lab':lab, 'form': form}
        return render(request, 'list_lab.html', context)
    

    def post(self, request, pk):
        lab = get_object_or_404(Laboratory, pk=pk)
        return render(request, 'list_lab.html', {'lab':lab})

main/views/dashboard.py
from django.views.generic import View
from ..models import Usuario
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from laboratory.forms.schedule_lab_form import ScheduleLabForm
from laboratory.models import Laboratory


class Dashboard(LoginRequiredMixin, View):

    def get(self, request, username):
        user = get_object_or_404(Usuario, username=username)
        lab_active = Laboratory.objects.filter(is_active=True).values('pk','name_laboratory', 'number_laboratory')
        if lab_active:

            context = {'user': user, 'lab_active': lab_active}

            return render(request, 'dashboard.html', context)
        
        return render(request, 'dashboard.html', {'user': user, 'lab_active': []})

main/views/login.py
from django.views import View
from django.shortcuts import render, redirect
from ..forms.login_forms import LoginForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.core.exceptions import PermissionDenied
from main.models import Usuario


class Login(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('dashboard.html', username=request.user.username)
        
        form = LoginForm()
        formulario = {'form': form}

        return render(request, 'login.html', formulario)
    
    def post(self, request):
        if request.method == "POST":
            form = LoginForm(request, request.POST)
        
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('dashboard', username=request.user.username)
                
            else:
                try:
                    user = Usuario.objects.get(username=username)

                    if not user.is_active:
                        raise PermissionDenied('Usuário inativo, entre em contato com o administrador')
                    
                    authenticated_user = authenticate(request, username=username, password=password)

                    if authenticated_user is None:
                        messages.error(request, 'Credenciais Inválida')
                        return render(request, 'login.html', {'form':form})
                    
                except Usuario.DoesNotExist:
                    messages.error(request, 'Usuário não existe')
                    return render(request, 'login.html', {'form':form})
                
                except PermissionDenied as e:
                    messages.error(request, 'Usuário não cadastrado')
                    return render(request, 'login.html', {'form':form})
                
                except Exception as e:
                    messages.error(request, 'Erro desconhecido')
                    return render(request, 'login.html', {'form':form})
        else:
            form = LoginForm()
            formulario = {'form': form}
            return render(request, 'login.html', formulario)

main/views/signup.py
# from django.views import View
# from django.shortcuts import render
# from django.urls import reverse
# from django.http import HttpResponseRedirect
# from ..models import Usuario
# from ..forms.signup_forms import SignupForms
# from django.contrib import messages
# from django.contrib.auth import login


# class Signup(View):
#     def get(self, request):
#         form = SignupForms()
#         data = {'form': form}

#         return render(request, 'signup.html', data)
    

#     def post(self, request):
        
#         form = SignupForms(request.POST)

#         if form.is_valid():
            
#             username = form.cleaned_data['username']
#             password1 = form.cleaned_data['password1']
#             password2 = form.cleaned_data['password2']
#             print(username)
#             print(password1)
#             print(password2)

#             if password1 == password2:

#                 if Usuario.objects.filter(username=username).exists():
#                     messages.error(request, 'O nome do usuário já existe')
                
#                 else:
#                     user = Usuario.objects.create_user(username=username, password=password1)
#                     if user is not None:
#                         login(request, user)
#                         return HttpResponseRedirect(reverse('dashboard', kwargs={'username':username}))

#             else:
#                 messages.error(request, 'As senhas não são iguais, tente novamente.')

#         form = {'form': form}

#         return render(request, 'signup.html', form)




from django.views import View
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from ..models import Usuario
from ..forms.signup_forms import SignupForms
from django.contrib import messages
from django.contrib.auth import login


class Signup(View):
    def get(self, request):
        form = SignupForms()
        data = {'form': form}

        return render(request, 'signup.html', data)
    

    def post(self, request):
        
        form = SignupForms(request.POST)

        if form.is_valid():

            username = form.cleaned_data['username']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']

            if password1 == password2:

                if Usuario.objects.filter(username=username).exists():
                    messages.error(request, 'Usuário já existe')
                
                else:
                    
                    user = Usuario.objects.create_user(username=username, password=password1)

                    if user is not None:
                        user.backend = 'django.contrib.auth.backends.ModelBackend'
                        login(request, user)
                        return HttpResponseRedirect(reverse('dashboard', kwargs={'username':username}))

        form = {'form': form}

        return render(request, 'signup.html', form)
    

main/views/update_user.py
from django.views import View
from django.shortcuts import render, redirect
from ..models import Usuario
from ..forms.updateuser_forms import UserUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages


class UpdateUser(LoginRequiredMixin, View):

    template_name = 'update_user.html'

    def get(self, request, pk):
        user = Usuario.objects.get(pk=pk)
        form = UserUpdateForm(instance=user)
        return render(request, self.template_name, {'form': form})


    def post(self, request, pk):
        user = Usuario.objects.get(pk=pk)
        form = UserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            cpf_cnpj = form.cleaned_data['cpf_cnpj']
            email = form.cleaned_data['email']
            if Usuario.objects.filter(cpf_cnpj=cpf_cnpj).exists():
                messages.error(request, 'CPF ou CNPJ já existe')
            elif Usuario.objects.filter(email=email).exists():
                messages.error(request, 'Email já existe')
            else:
                form.save()
                messages.success(request, 'Atualização realizada com sucesso.')

            return redirect('updateuser', pk=pk)
        messages.error(request, 'erro na atualização do cadastro')

        return render(request, self.template_name, {'form': form})

templates/404_error.html
<!-- templates/errors/error_404.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Erro 404 ATIVO</title>
</head>
<body>
    <h1>Página não encontrada</h1>
    <p>A página que você está procurando não existe.</p>
</body>
</html>

templates/dashboard.html
{% load static %}
<html>


<body>

    <head>
        <meta charset="UTF-8" />
        <title>Dashboard</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <link rel="stylesheet" type="text/css" href="{% static 'styles/style_dashboard.css'%}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
       
    </head>
      <header> 
        <div class="bem-vindo">
        <a href="{% url 'index' %}"><button class="button_voltar" >Home</button></a>
        <a href="{% url 'logout' %}"> <button class="button_logout">Logout</button> </a>
    </div> 
          
          
      </header>
        <div class="container" >
          <a class="links" id="paracadastro"></a>
          <a class="links" id="paralogin"></a>
          
           
     <!--  </div>
    {% if user.is_authenticated %}
        <h1>Bem-vindo, {{ user.username }}!</h1>
    {% else %}
        {% url login %}
    {% endif %} -->
    <div class="content">
        <div id="login">
            <h1>Faça sua Reserva de Laboratório</h1>
            <form method="post">
                {% csrf_token %}
                {% for lab in lab_active %}
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Num Laboratório</th>
                            <th>Nome Laboratório</th>
                            <th>Agendamento Laboratório</th>
                        </tr>
                    </thead>
                    <tbody>
                            <tr>
                                <td>{{ lab.number_laboratory }}</td>
                                <td>{{ lab.name_laboratory }}</td>

                                <a href="{% url 'laboratorio:list_lab' lab.pk %}">
                                <td>
                                     <a href="{% url 'laboratorio:list_lab' lab.pk %}">Agendar</a>
                                    
                                </td>
                                </a>
                            </tr>
                    </tbody>
                </table><br><br>
                {% endfor %}
            </form>
        </div>
    </div>
</body>
</html>

templates/index.html
{% load static %}


<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StudentPro</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>

<body>
    <div class="pagina-inicial">
        <header class="cabecalho">
            <img  class="Logo-StudentPro" src="{% static 'assets/logo/logo3.png' %}">
            <!--<div class="cabecalho__busca">
                <div class="busca__fundo">
                    <input class="busca__input" type="text" placeholder="O que você procura?">
                    <img class="busca__icone" src="{% static 'assets/ícones/1x/search.png' %}" alt="ícone de search">
                </div>
            </div>-->
        </header>
        <section class="sobre">
            <div class="extras">
                
            </div>

        </section>
        <main class="principal">
            <section class="menu-lateral">
                <nav class="menu-lateral__navegacao">
                    <a href="{% url 'index' %}"><img src="{% static 'assets/ícones/1x/Home - ativo.png' %}"> Home</a>
                    <a href="{% url 'dashboard' username=user %}"><img src="{% static 'assets/ícones/1x/Mais vistas - inativo.png' %}">Reserva de Laboratório</a>
                    <a href="{% url 'updateuser' pk=user.pk %}"><img src="{% static 'assets/ícones/1x/Novas - inativo.png' %}"> Atualizar user</a>
                    <a href="{% url 'logout' %}"><img src="{% static 'assets/ícones/1x/Surpreenda-me - inativo.png' %}"> Sair</a>
                </nav>
            </section>
            <section class="conteudo">
                <section class="banner">
                    <img class="banner__imagem" src="{% static 'assets/imagens/estud.png' %}" alt="banner StudentPro">
                    <h1 class="banner__titulo"></h1>
                </section>
                <section class="tags">

                </section>
            
   
</body>

</html>

templates/list_lab.html
<html>
<body>
    <a href="{% url 'logout' %}">Logout</a><BR><BR>
    <a href="{% url 'updateuser' pk=user.pk %}">Atualizar</a><br><br>
    <a href="{% url 'dashboard' username=user.username %}">Dashboard</a>
    
    {% if user.is_authenticated %}
        <h1>Olá, {{ user.username }}, vamos fazer o seu agendamento!</h1>
    {% else %}
        {% url login %}
    {% endif %}
        <form method="post">
            {% csrf_token %}
            <table>
                <thead>
                    <tr>
                        <th>Num Laboratório</th>
                        <th>Nome Laboratório</th>
                    </tr>
                </thead>
                <tbody>
                        <tr>
                            <td>{{ lab.number_laboratory }}</td>
                            <td>{{ lab.name_laboratory }}</td>
                            <td>{{ form.as_table }}</td>
                            <td><button type="submit" style="margin-bottom: 50px;">Agendar</button></td>
                            
                        </tr>
                </tbody>
            </table>
        </form>
</body>
</html>

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'styles/style_login.css'%}">
    <title>Login</title>
</head>
<body>
    <div class="main-login">
        <div class="left-login">
            <h1>Faça login<br>E entre para nossa instituição!</h1>
            <img class="left-login-image"  src="{% static 'assets/imagens/imagemlogin.svg' %}" alt="estudantes">
        </div>
        <div class="right-login">
            <div class="card-login">
                <h1><b>LOGIN</b></h1>
                <div class="textfield">
                    {% if messages %}
                    {% for message in messages %}
                    <ul class="messages"></ul>
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                        <form action="{% url 'login' %}" method="POST">
                            {% csrf_token %}
                            {% for field in form.visible_fields %}
                            <div class="textfield">
                                    <label for="{{ field.id_for_label }}"> {{field.label}} </label>
                                    {{ field }}
                            </div>  
                            {% endfor %}
                            <div>
                                <a href= "{% url 'signup' %} "> Cadastra-se </a>
                            </div>
                            <div> 
                                <button class="btn-login" type="submit">Login</button>
                            </div>
                           
                        </form>
                </div>

                
        </div>
    </div>
</body>
</html>

templates/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style_telacadastro.css' %}">
    <title>Formulário de Cadastro</title>
</head>
<body>
    <div class="container">
        <div class="form-image">
            <img src="{% static 'assets/imagens/imagem2_cadastro.svg' %}">
        </div>
        <div class="form">
            <form method="post" action="{% url 'signup' %}">
                {% csrf_token %}
                {% for field in form.visible_fields %}
                <div class="input-box">
                        <label for="{{ field.id_for_label }}"> {{field.label}} </label>
                        {{ field }}
                </div>  
                {% endfor %} 
                <div class="login-button">
                    <button class="btn-login" type="submit">Registrar</button>
                </div>

                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
        </div>
        
    </div>
</body>
</html>

templates/update_user.html
{% load static%}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style_edicao_usuario.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
       
</head>

<body>
    <div class="container">
        <div class="form-image">
            <img src="{% static 'assets/imagens/imagem_edicao_usuario.jpg' %}">
        </div>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div class="{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}
    
    <div class="form">
        <form action="{% url 'updateuser' pk=user.pk %}", method="post">
            {% csrf_token %}
            <div class="form-header">
                <div class="title">
                    <h1> Edição de Usuário</h1>
                </div>
                <div class="login-button"></div>
            </div>

            <div class="row">
                {% for field in form.visible_fields %}
                <div class="col-12" style="margin-bottom: 10px;">
                    <label for="{{ field.id_for_label }}" style="color:black; margin-bottom: 5px;">{{field.label}}</label>
                    {{ field }}
                </div>
                {% endfor %}
            </div>
        </form>
        <div>
            <button class="button_salvar_alteracoes"  type="submit">Salvar Alterações</button> 
    </div>             
        
</body>
</html>